[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = "1.0.219"
ts-rs = "10.1"
tokio = { version = "1", features = ["full"] }
hyper = { version = "1", features = ["full"] }

http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }

sqlx = { version = "0.8", features = [ "runtime-tokio" ] }
