// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comparison } from "./Comparison";
import type { NumberExpression } from "./NumberExpression";

export type BooleanExpression = { "Literal": boolean } | { "Comparison": { a: NumberExpression, compared_to: Comparison, b: NumberExpression, } };
