// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RankExpression } from "./RankExpression";
import type { SuitExpression } from "./SuitExpression";
import type { ZoneExpression } from "./ZoneExpression";

export type CardCollectionExpression = { "GetVariable": string } | { "InZoneMatchingSuit": { zone: ZoneExpression, suit: SuitExpression, } } | { "InZoneMatchingRank": { zone: ZoneExpression, rank: RankExpression, } };
