// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rank } from "./Rank";
import type { Suit } from "./Suit";

export type CardSelector = "Top" | "Bottom" | { "Suit": Suit } | { "Rank": Rank };
