// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RankExpression } from "./RankExpression";
import type { SuitExpression } from "./SuitExpression";

export type CardExpression = { "Create": [SuitExpression, RankExpression] };
