// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardExpression } from "./CardExpression";
import type { ZoneExpression } from "./ZoneExpression";

export type CardSetExpression = { "Single": CardExpression } | { "GetVariable": string } | { "ZoneTopCard": ZoneExpression } | { "ZoneBottomCard": ZoneExpression } | { "ZoneAllCards": ZoneExpression };
