// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ZoneExpression } from "./ZoneExpression";

export type ChoiceAction = { "MoveCards": { from: ZoneExpression, to: ZoneExpression, } };
