// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChoiceSelectionEnum } from "./ChoiceSelectionEnum";

export type ChoiceSelection = { name: string, choice_type: ChoiceSelectionEnum, };
