// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardCollectionExpression } from "./CardCollectionExpression";
import type { PlayerCollectionExpression } from "./PlayerCollectionExpression";

export type ChoiceSelectionEnum = { "Player": PlayerCollectionExpression } | { "PlayerSelection": PlayerCollectionExpression } | { "Card": CardCollectionExpression } | { "CardSelection": CardCollectionExpression };
