// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BooleanExpression } from "./BooleanExpression";
import type { Statement } from "./Statement";

export type ConditionalStatement = { condition: BooleanExpression, go_true: Statement, go_false: Statement, };
