// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BooleanExpression } from "./BooleanExpression";
import type { CardSelectorExpression } from "./CardSelectorExpression";
import type { NumberExpression } from "./NumberExpression";
import type { PlayerCollectionExpression } from "./PlayerCollectionExpression";
import type { PlayerExpression } from "./PlayerExpression";
import type { RankExpression } from "./RankExpression";
import type { SuitExpression } from "./SuitExpression";
import type { ZoneCollectionExpression } from "./ZoneCollectionExpression";
import type { ZoneExpression } from "./ZoneExpression";

export type Expression = { "Number": NumberExpression } | { "Boolean": BooleanExpression } | { "Zone": ZoneExpression } | { "ZoneCollection": ZoneCollectionExpression } | { "Player": PlayerExpression } | { "PlayerCollection": PlayerCollectionExpression } | { "Suit": SuitExpression } | { "Rank": RankExpression } | { "CardSelector": CardSelectorExpression };
