// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";
import type { GameAction } from "./GameAction";
import type { GameStatus } from "./GameStatus";
import type { PlayerSnapshot } from "./PlayerSnapshot";
import type { ZoneSnapshot } from "./ZoneSnapshot";

export type GameSnapshot = { actions: Array<GameAction>, private_actions: Array<GameAction>, players: PlayerSnapshot | null, status: GameStatus, public_cards: { [key in number]?: Card }, zones: Array<ZoneSnapshot>, };
