// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameWaitingStatus } from "./GameWaitingStatus";

export type GameStatus = { "Waiting": GameWaitingStatus } | "Playing" | "Invalid";
