// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pattern } from "./Pattern";
import type { Phase } from "./Phase";
import type { PlayerClass } from "./PlayerClass";
import type { Rank } from "./Rank";
import type { RankOrder } from "./RankOrder";
import type { Suit } from "./Suit";
import type { ZoneClass } from "./ZoneClass";

export type GameConfig = { allowed_ranks: Array<Rank>, allowed_suits: Array<Suit>, orders: { [key in string]?: RankOrder }, patterns: { [key in string]?: Array<Pattern> }, phases: { [key in string]?: Phase }, zone_classes: { [key in string]?: ZoneClass }, player_classes: { [key in string]?: PlayerClass }, player_zones: { [key in string]?: string }, player_assignment: Array<string>, initial_zones: { [key in string]?: string }, initial_phase: string, player_range: { start: number, end: number, }, numbers: Array<string>, };
