// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameChat } from "./GameChat";

export type GameAction = "SetCards" | "Layout" | "Private" | { "JoinResult": { Ok : string } | { Err : string } } | { "ChatMsg": GameChat };
