// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultiPlayerTarget } from "./MultiPlayerTarget";

export type MultiZoneTarget = { "Player": { player: MultiPlayerTarget, zone: { [key in string]?: string }, } };
