// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RankOrder } from "./RankOrder";
import type { SingleZoneTarget } from "./SingleZoneTarget";

export type NumberExpression = { "Literal": bigint } | { "SumZones": { zone: SingleZoneTarget, ordering: RankOrder, } };
