// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BooleanExpression } from "./BooleanExpression";
import type { OfferChoice } from "./OfferChoice";
import type { Statement } from "./Statement";

export type OfferCase = { condition: BooleanExpression | null, choices: Array<OfferChoice>, handle: Statement, message: string, };
