// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfferCase } from "./OfferCase";
import type { PlayerCollectionExpression } from "./PlayerCollectionExpression";

export type Offer = { player_name: string | null, offer_to: PlayerCollectionExpression, cases: Array<OfferCase>, };
