// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatternPiece } from "./PatternPiece";
import type { Rank } from "./Rank";
import type { Relation } from "./Relation";
import type { Suit } from "./Suit";

export type Pattern = { "Relation": Relation } | { "Suit": Array<PatternPiece<Suit | null>> } | { "Rank": Array<PatternPiece<Rank | null>> };
