// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerRole } from "./PlayerRole";

export type PlayerInformation = { nickname: string, role: PlayerRole | null, disconnected: bigint | null, };
