// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerTarget } from "./PlayerTarget";

export type PlayerCollectionExpression = { "PlayerCollection": PlayerTarget };
