// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerInformation } from "./PlayerInformation";

export type PlayerSnapshot = { players: { [key in string]?: PlayerInformation }, order: Array<string>, };
