// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerAssignmentRule } from "./PlayerAssignmentRule";

export type PlayerClass = { zones: { [key in string]?: string }, assignment_rule: PlayerAssignmentRule, };
