// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rank } from "./Rank";

export type RankOrder = { order: Array<Rank>, rank_to_index: { [key in Rank]?: number }, };
