// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardExpression } from "./CardExpression";
import type { Rank } from "./Rank";

export type RankExpression = { "Literal": Rank } | { "FromCard": CardExpression };
