// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pagination } from "./Pagination";
import type { RulesetPreview } from "./RulesetPreview";

export type RulesetListing = { total: bigint, pagination: Pagination, contents: Array<RulesetPreview>, };
