// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RulesetPreview = { title: string, description: string, author_id: string, author_name: string, based_on: string | null, ruleset_id: string, };
