// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SinglePlayerTarget } from "./SinglePlayerTarget";

export type SingleZoneTarget = { "Existing": string } | { "Player": { player: SinglePlayerTarget, zone: { [key in string]?: string }, } } | { "Create": string };
