// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardExpression } from "./CardExpression";
import type { Suit } from "./Suit";

export type SuitExpression = { "Literal": Suit } | { "FromCard": CardExpression };
