// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultiZoneTarget } from "./MultiZoneTarget";
import type { SingleZoneTarget } from "./SingleZoneTarget";

export type ZoneTarget = { "Single": SingleZoneTarget } | { "Multiple": MultiZoneTarget };
