// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ZoneSnapshot = { cards: Array<number>, owner: number | null, display_name: string | null, zone_id: number, };
