// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ZoneCleanupBehavior } from "./ZoneCleanupBehavior";
import type { ZoneVisibility } from "./ZoneVisibility";

export type ZoneClass = { visibility: ZoneVisibility, cleanup: ZoneCleanupBehavior, rules: Array<string>, };
