// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerExpression } from "./PlayerExpression";

export type ZoneExpression = { "OwnedByPlayer": { player: PlayerExpression, zone_name: string, } } | { "GetVariable": string };
