/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestImport } from './routes/test'
import { Route as CreateGameImport } from './routes/create-game'
import { Route as CardsImport } from './routes/cards'
import { Route as IndexImport } from './routes/index'
import { Route as GamesGameIdImport } from './routes/games/$gameId'

// Create/Update Routes

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const CreateGameRoute = CreateGameImport.update({
  id: '/create-game',
  path: '/create-game',
  getParentRoute: () => rootRoute,
} as any)

const CardsRoute = CardsImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GamesGameIdRoute = GamesGameIdImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsImport
      parentRoute: typeof rootRoute
    }
    '/create-game': {
      id: '/create-game'
      path: '/create-game'
      fullPath: '/create-game'
      preLoaderRoute: typeof CreateGameImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/create-game': typeof CreateGameRoute
  '/test': typeof TestRoute
  '/games/$gameId': typeof GamesGameIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/create-game': typeof CreateGameRoute
  '/test': typeof TestRoute
  '/games/$gameId': typeof GamesGameIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/create-game': typeof CreateGameRoute
  '/test': typeof TestRoute
  '/games/$gameId': typeof GamesGameIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cards' | '/create-game' | '/test' | '/games/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cards' | '/create-game' | '/test' | '/games/$gameId'
  id: '__root__' | '/' | '/cards' | '/create-game' | '/test' | '/games/$gameId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  CreateGameRoute: typeof CreateGameRoute
  TestRoute: typeof TestRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  CreateGameRoute: CreateGameRoute,
  TestRoute: TestRoute,
  GamesGameIdRoute: GamesGameIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cards",
        "/create-game",
        "/test",
        "/games/$gameId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cards": {
      "filePath": "cards.tsx"
    },
    "/create-game": {
      "filePath": "create-game.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/games/$gameId": {
      "filePath": "games/$gameId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
