/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as CreateGameImport } from './routes/create-game'
import { Route as CardsImport } from './routes/cards'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as GamesGameIdImport } from './routes/games/$gameId'
import { Route as RulesetsRulesetIdEditImport } from './routes/rulesets/$rulesetId/edit'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CreateGameRoute = CreateGameImport.update({
  id: '/create-game',
  path: '/create-game',
  getParentRoute: () => rootRoute,
} as any)

const CardsRoute = CardsImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GamesGameIdRoute = GamesGameIdImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRoute,
} as any)

const RulesetsRulesetIdEditRoute = RulesetsRulesetIdEditImport.update({
  id: '/rulesets/$rulesetId/edit',
  path: '/rulesets/$rulesetId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsImport
      parentRoute: typeof rootRoute
    }
    '/create-game': {
      id: '/create-game'
      path: '/create-game'
      fullPath: '/create-game'
      preLoaderRoute: typeof CreateGameImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdImport
      parentRoute: typeof rootRoute
    }
    '/rulesets/$rulesetId/edit': {
      id: '/rulesets/$rulesetId/edit'
      path: '/rulesets/$rulesetId/edit'
      fullPath: '/rulesets/$rulesetId/edit'
      preLoaderRoute: typeof RulesetsRulesetIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards': typeof CardsRoute
  '/create-game': typeof CreateGameRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/rulesets/$rulesetId/edit': typeof RulesetsRulesetIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards': typeof CardsRoute
  '/create-game': typeof CreateGameRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/rulesets/$rulesetId/edit': typeof RulesetsRulesetIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards': typeof CardsRoute
  '/create-game': typeof CreateGameRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/rulesets/$rulesetId/edit': typeof RulesetsRulesetIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cards'
    | '/create-game'
    | '/login'
    | '/signup'
    | '/games/$gameId'
    | '/rulesets/$rulesetId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cards'
    | '/create-game'
    | '/login'
    | '/signup'
    | '/games/$gameId'
    | '/rulesets/$rulesetId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cards'
    | '/create-game'
    | '/login'
    | '/signup'
    | '/games/$gameId'
    | '/rulesets/$rulesetId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CardsRoute: typeof CardsRoute
  CreateGameRoute: typeof CreateGameRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  RulesetsRulesetIdEditRoute: typeof RulesetsRulesetIdEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CardsRoute: CardsRoute,
  CreateGameRoute: CreateGameRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  RulesetsRulesetIdEditRoute: RulesetsRulesetIdEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/cards",
        "/create-game",
        "/login",
        "/signup",
        "/games/$gameId",
        "/rulesets/$rulesetId/edit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/cards": {
      "filePath": "cards.tsx"
    },
    "/create-game": {
      "filePath": "create-game.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/games/$gameId": {
      "filePath": "games/$gameId.tsx"
    },
    "/rulesets/$rulesetId/edit": {
      "filePath": "rulesets/$rulesetId/edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
