/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ProfileImport } from './routes/profile'
import { Route as LoginImport } from './routes/login'
import { Route as ListingImport } from './routes/listing'
import { Route as CardsImport } from './routes/cards'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as UserUsernameImport } from './routes/user/$username'
import { Route as RulesetsCreateImport } from './routes/rulesets/create'
import { Route as GamesGameIdImport } from './routes/games/$gameId'
import { Route as RulesetsRulesetIdStartImport } from './routes/rulesets/$rulesetId/start'
import { Route as RulesetsRulesetIdEditImport } from './routes/rulesets/$rulesetId/edit'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ListingRoute = ListingImport.update({
  id: '/listing',
  path: '/listing',
  getParentRoute: () => rootRoute,
} as any)

const CardsRoute = CardsImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserUsernameRoute = UserUsernameImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRoute,
} as any)

const RulesetsCreateRoute = RulesetsCreateImport.update({
  id: '/rulesets/create',
  path: '/rulesets/create',
  getParentRoute: () => rootRoute,
} as any)

const GamesGameIdRoute = GamesGameIdImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRoute,
} as any)

const RulesetsRulesetIdStartRoute = RulesetsRulesetIdStartImport.update({
  id: '/rulesets/$rulesetId/start',
  path: '/rulesets/$rulesetId/start',
  getParentRoute: () => rootRoute,
} as any)

const RulesetsRulesetIdEditRoute = RulesetsRulesetIdEditImport.update({
  id: '/rulesets/$rulesetId/edit',
  path: '/rulesets/$rulesetId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsImport
      parentRoute: typeof rootRoute
    }
    '/listing': {
      id: '/listing'
      path: '/listing'
      fullPath: '/listing'
      preLoaderRoute: typeof ListingImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdImport
      parentRoute: typeof rootRoute
    }
    '/rulesets/create': {
      id: '/rulesets/create'
      path: '/rulesets/create'
      fullPath: '/rulesets/create'
      preLoaderRoute: typeof RulesetsCreateImport
      parentRoute: typeof rootRoute
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameImport
      parentRoute: typeof rootRoute
    }
    '/rulesets/$rulesetId/edit': {
      id: '/rulesets/$rulesetId/edit'
      path: '/rulesets/$rulesetId/edit'
      fullPath: '/rulesets/$rulesetId/edit'
      preLoaderRoute: typeof RulesetsRulesetIdEditImport
      parentRoute: typeof rootRoute
    }
    '/rulesets/$rulesetId/start': {
      id: '/rulesets/$rulesetId/start'
      path: '/rulesets/$rulesetId/start'
      fullPath: '/rulesets/$rulesetId/start'
      preLoaderRoute: typeof RulesetsRulesetIdStartImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards': typeof CardsRoute
  '/listing': typeof ListingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/rulesets/create': typeof RulesetsCreateRoute
  '/user/$username': typeof UserUsernameRoute
  '/rulesets/$rulesetId/edit': typeof RulesetsRulesetIdEditRoute
  '/rulesets/$rulesetId/start': typeof RulesetsRulesetIdStartRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards': typeof CardsRoute
  '/listing': typeof ListingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/rulesets/create': typeof RulesetsCreateRoute
  '/user/$username': typeof UserUsernameRoute
  '/rulesets/$rulesetId/edit': typeof RulesetsRulesetIdEditRoute
  '/rulesets/$rulesetId/start': typeof RulesetsRulesetIdStartRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards': typeof CardsRoute
  '/listing': typeof ListingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/rulesets/create': typeof RulesetsCreateRoute
  '/user/$username': typeof UserUsernameRoute
  '/rulesets/$rulesetId/edit': typeof RulesetsRulesetIdEditRoute
  '/rulesets/$rulesetId/start': typeof RulesetsRulesetIdStartRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cards'
    | '/listing'
    | '/login'
    | '/profile'
    | '/signup'
    | '/games/$gameId'
    | '/rulesets/create'
    | '/user/$username'
    | '/rulesets/$rulesetId/edit'
    | '/rulesets/$rulesetId/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cards'
    | '/listing'
    | '/login'
    | '/profile'
    | '/signup'
    | '/games/$gameId'
    | '/rulesets/create'
    | '/user/$username'
    | '/rulesets/$rulesetId/edit'
    | '/rulesets/$rulesetId/start'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cards'
    | '/listing'
    | '/login'
    | '/profile'
    | '/signup'
    | '/games/$gameId'
    | '/rulesets/create'
    | '/user/$username'
    | '/rulesets/$rulesetId/edit'
    | '/rulesets/$rulesetId/start'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CardsRoute: typeof CardsRoute
  ListingRoute: typeof ListingRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  RulesetsCreateRoute: typeof RulesetsCreateRoute
  UserUsernameRoute: typeof UserUsernameRoute
  RulesetsRulesetIdEditRoute: typeof RulesetsRulesetIdEditRoute
  RulesetsRulesetIdStartRoute: typeof RulesetsRulesetIdStartRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CardsRoute: CardsRoute,
  ListingRoute: ListingRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  RulesetsCreateRoute: RulesetsCreateRoute,
  UserUsernameRoute: UserUsernameRoute,
  RulesetsRulesetIdEditRoute: RulesetsRulesetIdEditRoute,
  RulesetsRulesetIdStartRoute: RulesetsRulesetIdStartRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/cards",
        "/listing",
        "/login",
        "/profile",
        "/signup",
        "/games/$gameId",
        "/rulesets/create",
        "/user/$username",
        "/rulesets/$rulesetId/edit",
        "/rulesets/$rulesetId/start"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/cards": {
      "filePath": "cards.tsx"
    },
    "/listing": {
      "filePath": "listing.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/games/$gameId": {
      "filePath": "games/$gameId.tsx"
    },
    "/rulesets/create": {
      "filePath": "rulesets/create.tsx"
    },
    "/user/$username": {
      "filePath": "user/$username.tsx"
    },
    "/rulesets/$rulesetId/edit": {
      "filePath": "rulesets/$rulesetId/edit.tsx"
    },
    "/rulesets/$rulesetId/start": {
      "filePath": "rulesets/$rulesetId/start.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
