use rand::seq::IndexedRandom;

const ADJECTIVES: &[&str] = &[
    "Anonymous",
    "Brave",
    "Calm",
    "Daring",
    "Eager",
    "Frank",
    "Gentle",
    "Happy",
    "Invisible",
    "Jolly",
    "Kind",
    "Lucky",
    "Modest",
    "Noble",
    "Open",
    "Patient",
    "Quiet",
    "Resilient",
    "Serene",
    "True",
    "United",
    "Vibrant",
    "Wise",
    "Youthful",
    "Zealous",
    "Alert",
    "Bold",
    "Charming",
    "Diligent",
    "Earnest",
    "Fearless",
    "Gracious",
    "Honest",
    "Ingenious",
    "Keen",
    "Lively",
    "Merry",
    "Neat",
    "Optimistic",
    "Polite",
    "Resourceful",
    "Sincere",
    "Thoughtful",
    "Upbeat",
    "Valiant",
    "Witty",
    "Zesty",
];

const NOUNS: &[&str] = &[
    "Antelope",
    "Badger",
    "Cardinal",
    "Dolphin",
    "Eagle",
    "Fox",
    "Gazelle",
    "Hawk",
    "Iguana",
    "Jaguar",
    "Koala",
    "Lion",
    "Monkey",
    "Newt",
    "Owl",
    "Panda",
    "Quail",
    "Rabbit",
    "Squirrel",
    "Tiger",
    "Urial",
    "Vole",
    "Wolf",
    "Xerus",
    "Yak",
    "Zebra",
    "Albatross",
    "Beaver",
    "Cougar",
    "Deer",
    "Elephant",
    "Ferret",
    "Giraffe",
    "Hyena",
    "Impala",
    "Jackal",
    "Kangaroo",
    "Leopard",
    "Mongoose",
    "Narwhal",
    "Octopus",
    "Penguin",
    "Quokka",
    "Raccoon",
    "Sloth",
    "Toucan",
    "Viper",
    "Weasel",
    "Walrus",
    "Wombat",
];

pub fn make_random_name() -> String {
    let mut rng = rand::rng();

    let adjective = ADJECTIVES.choose(&mut rng).unwrap_or(&"Anonymous");
    let noun = NOUNS.choose(&mut rng).unwrap_or(&"Animal");

    format!("{}{}", adjective, noun)
}
